thinkster-django-angular-boilerplate/thinkster_django_angular_boilerplate/urls.py
from django.conf.urls import patterns, url, include

from thinkster_django_angular_boilerplate.views import IndexView

from authentication.views import LoginView, LogoutView, UserView

from books.views import SearchView, HomeView, BookView, ConfirmationView, book_search, recommendations
import authentication

# .. Imports
from rest_framework_nested import routers

from authentication.views import AccountViewSet



router = routers.SimpleRouter()
router.register(r'accounts', AccountViewSet)

urlpatterns = patterns(
     '',
    # ... URLs
    url(r'^api/v1/', include(router.urls)),

    url(r'^api/v1/auth/login/$', LoginView.as_view(), name='login'),

    url(r'^api/v1/auth/logout/$', LogoutView.as_view(), name='logout'),   

    url(r'^search/$', book_search, name='search_books'),
	
	url(r'^book/([a-zA-Z0-9-]+)$', BookView.as_view(), name='book_info'),

    url(r'^account/([a-zA-Z0-9-]+)$', authentication.views.user_account, name='user_info'),

    url(r'^confirmation/([a-zA-Z0-9-]+)$', ConfirmationView.as_view(), name='user_info'),

    url(r'^store_info/add/$', authentication.views.book_new, name='bookNew'),

    url(r'^store_info/edit/$', authentication.views.book_edit, name='bookEdit'),

    url(r'^edit/$', authentication.views.account_edit, name='accEdit'),

    url(r'^store_info/popularbook/$', authentication.views.book_popular, name='bookPopular'),

    url(r'^store_info/$', authentication.views.account_admin, name='adminpage'),

	url(r'^$', HomeView.as_view(), name='home_page'),

    url('^.*$', IndexView.as_view(), name='index')
)

thinkster-django-angular-boilerplate/books/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ValidationError
from authentication.models import Account
from django.core.validators import RegexValidator, MinValueValidator
class Book(models.Model):
    isbn10 = models.CharField(validators=[RegexValidator(regex='^.{10}$', message='Length has to be 10', code='nomatch')],primary_key=True, max_length=10)
    title = models.CharField(max_length=256)
    authors = models.CharField(max_length=256, blank=True, null=True)
    publisher = models.CharField(max_length=64, blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    stock = models.IntegerField()
    price = models.FloatField(validators = [MinValueValidator(0.0)],blank=True,default=0.0)
    formatchoices = (
        ('hardcover', 'hardcover'),
        ('paperback', 'paperback')
    )
    format = models.CharField(max_length=9, blank=True, null=True, choices=formatchoices)
    keyword = models.CharField(max_length=100, blank=True, null=True)
    subject = models.CharField(max_length=100, blank=True, null=True)
    image = models.CharField(max_length=256,blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'book'


class BookOrdered(models.Model):
    oid = models.ForeignKey('OrderHistory', db_column='oid')
    isbn10 = models.ForeignKey('Book', db_column='isbn10')
    quantity = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'book_ordered'
        unique_together = (('oid', 'isbn10'),)




# class DjangoMigrations(models.Model):
#     app = models.CharField(max_length=255)
#     name = models.CharField(max_length=255)
#     applied = models.DateTimeField()

#     class Meta:
#         managed = True
#         db_table = 'django_migrations'
#         app_label = 'mainpage'

class Feedback(models.Model):
    entry_date = models.DateField(auto_now_add=True, null=True)
    scorechoices = zip(range(0,11), range(0,11))
    score = models.IntegerField(choices=scorechoices)
    opinion = models.CharField(max_length=256, blank=True, null=True)
    login = models.ForeignKey(Account,to_field='username')
    isbn10 = models.ForeignKey('Book', db_column='isbn10')

    class Meta:
        managed = True
        db_table = 'feedback'
        unique_together = (('login', 'isbn10'),)


class OrderHistory(models.Model):
    oid = models.AutoField(primary_key=True)
    login = models.ForeignKey(Account,to_field='username', blank=True, null=True)
    order_date = models.DateField(auto_now_add=True,blank=True, null=True)
    statuschoices = (
        ('processing', 'processing order'),
        ('transit', 'in transit'),
        ('delivered', 'delivered')
    )
    order_status = models.CharField(max_length=16, blank=True, null=True, choices=statuschoices)

    class Meta:
        managed = True
        db_table = 'order_history'

class UsefulnessRating(models.Model):
    def clean(self):
        if (self.rater_id == self.ratee_id):
            raise ValidationError('rater_id == ratee _id')

    rater = models.ForeignKey(Account,to_field='username', related_name='rater')
    ratee = models.ForeignKey(Account,to_field='username', related_name='ratee')
    usefulnesschoices = (
        (0,0),
        (1,1),
        (2,2)
    )
    usefulness = models.IntegerField(choices=usefulnesschoices)
    isbn10 = models.ForeignKey(Book, db_column='isbn10')

    class Meta:
        managed = True
        db_table = 'usefulness_rating'
        unique_together = (('rater', 'ratee', 'isbn10'),)

thinkster-django-angular-boilerplate/authentication/forms.py
from django import forms
from books.models import Book, OrderHistory, Feedback
from authentication.models import Account

class AddBookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = '__all__'


class SearchBookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = ('isbn10',)

class EditBookForm(forms.ModelForm):
    bookset = Book.objects.all().order_by('isbn10')
    bookset=list(bookset)
    book_choices = [(bookset[i].isbn10,'('+bookset[i].isbn10+') '+bookset[i].title) for i in range(len(bookset))]
    isbn10 = forms.ChoiceField(choices=book_choices)

    stock = forms.IntegerField(min_value=1)
    class Meta:
        model = Book
        fields = ('isbn10','stock',)
		
		
class FilterBookForm(forms.Form):
    month_choices = (
        ('1', 'Jan'),
        ('2', 'Feb'),
        ('3', 'Mar'),
        ('4', 'Apr'),
        ('5', 'May'),
        ('6', 'Jun'),
        ('7', 'Jul'),
        ('8', 'Aug'),
        ('9', 'Sep'),
        ('10', 'Oct'),
        ('11', 'Nov'),
        ('12', 'Dec')
    )

    month = forms.ChoiceField(choices=month_choices)
    views = forms.IntegerField(min_value=1)
	
class FeedbackForm(forms.Form):
    ISBN10 = forms.CharField(
    widget=forms.TextInput(attrs={'readonly':'readonly'})
)
    title = forms.CharField(
    widget=forms.TextInput(attrs={'readonly':'readonly'})
)
    score = forms.IntegerField(min_value=0,max_value=10)
    opinion = forms.CharField(min_length=1)

class UsefulnessForm(forms.Form):
    ISBN10 = forms.CharField(
    widget=forms.TextInput(attrs={'readonly':'readonly'})
)
    title = forms.CharField(
    widget=forms.TextInput(attrs={'readonly':'readonly'})
)   
    rating_on = forms.CharField(
    widget=forms.TextInput(attrs={'readonly':'readonly'})
)   
    score = forms.IntegerField(min_value=0,max_value=2)

class AdvanceSearchForm(forms.Form):
    title = forms.CharField(required=False)
    authors = forms.CharField(required=False)
    publisher = forms.CharField(required=False)
    subject = forms.CharField(required=False)
    # class Meta:
    #     model = Book 
    #     fields = ('authors','publisher','title','subject',)


class UsefulFeedbackForm(forms.Form):
    top_n = forms.IntegerField(min_value=1,max_value=500)

class EditAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('full_name','credit_card','address','phone')

thinkster-django-angular-boilerplate/templates/addbook.html
<!DOCTYPE html>

<html ng-app="thinkster">
<head>
  <title>thinkster-django-angular-boilerplate</title>

  <base href="/" />

  {% include 'stylesheets.html' %}
</head>

<body >
  {% include 'navbar.html' %}
    	<div class="addbook">
    		<h4>{{msg}}</h4>
  		<div class="well">
    	<div class="margauto">

		{% block content %}
			
			<h1>Add Book</h1>
			<form role="form" action="" method="post">
			    {% csrf_token %}	
				<table class="addtable">
			    {{ form.as_table }}
				</table>
				<p>
			<div class="row smallmarg">
				<div class="col-md-6">
				</div>
				<div class="col-md-3">
					<button id="new" class="btn" type="submit">Submit</button>
				</div>
			</div>
			</form>
			{% endblock %}
				
	    	
   		</div>
    	</div>
    	</div>
  {% include 'javascripts.html' %}
</body>
</html>

thinkster-django-angular-boilerplate/templates/adminpage.html
<!DOCTYPE html>

<html ng-app="thinkster">
<head>
  <title>thinkster-django-angular-boilerplate</title>

  <base href="/" />

  {% include 'stylesheets.html' %}
</head>

<body >
  {% include 'navbar.html' %}
    <div class="container">
  		
    	<div class="well">
    		<h3>Inventory</h3>
    		
    		{%block content%}
    		<div class="scroll-review smallmarg">
				<table class="ftable">
					<tr>
						<th> S/N. </th>
						<th> isbn10	 </th>
						<th> title </th>
						<th> authors </th>
						<th> publisher </th>	
						<th> year </th>
						<th> stock </th>
						<th> price </th>
						<th> format </th>
						<th> keyword </th>
						<th> subject </th>
						
					</tr>
					{% for entry in data %}
					<tr>
						<td>{{entry.id}}</td>
						<td>{{entry.isbn10}}</td>
						<td>{{entry.title}}</td>
						<td>{{entry.authors}}</td>
						<td>{{entry.publisher}}</td>
						<td>{{entry.year}}</td>
						<td>{{entry.stock}}</td>
						<td>{{entry.price}}</td>
						<td>{{entry.format}}</td>
						<td>{{entry.keyword}}</td>
						<td>{{entry.subject}}</td>

					</tr>
					{% endfor %}

				</table>
				
				<p>
			</div>
			<div class="row smallmarg">
				<div class="col-md-6">
				</div>
				<div class="col-md-2">
					<button id="add" class="btn" onclick = "location.href='/store_info/add/'"> Add new book </button>
				</div>
				<div class="col-md-2 tar">
					<button id="edit" class="btn" onclick = "location.href='/store_info/edit/'"> Edit book </button>
				</div>
				<div class="col-md-2 tac">
					<button id="top" class="btn" onclick = "location.href='/store_info/popularbook/'"> Top books </button>
				</div>
			</div>
				
				
				
			{% endblock%}
		
    	</div>
    </div>
  {% include 'javascripts.html' %}
</body>
</html>

thinkster-django-angular-boilerplate/templates/book_info.html
<!DOCTYPE html>

<html ng-app="thinkster">
<head>
  <title>thinkster-django-angular-boilerplate</title>

  <base href="/" />

  {% include 'stylesheets.html' %}
</head>

<body  ng-controller="BookInfoController">
  {% include 'navbar.html' %}
  <div id="usefulnessModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">

	    <!-- Modal content-->
	    <div class="modal-content">
	    <form role="form" action="" method="post">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Rate Usefulness of Feedback</h4>
	        <h5>Please give this feedback a score of 0, 1, or 2 (’useless’, ’useful’, ’very useful’ respectively). </h5>
	      </div>
		      <div class="modal-body">
		      	<div class="well">
		      	{% block content %}
				
				
				    {% csrf_token %}	
					<table class="addtable">
				    {{ form.as_table }}
					</table>
					<p>

				
				{% endblock %}

		    	</div>
		      </div>
		      <div class="modal-footer">
		        <div class="form-group">
		          <button class="btn btn-primary pull-right"  type="submit">RATE USER FEEDBACK</button>
		        </div>
		      </div>
		      </form>
	    </div>

	  </div>
	</div>
  <div class="container">
    <h3>{{bookinfo.title}}</h3>
    <h5>by {{bookinfo.authors}}</h5>
    <div class="row">
		<div class="col-md-5"><img src="static/images/{{bookinfo.image}}" class="center"></div>
		<div class="col-md-7">
			<ul class="nav nav-tabs">
			  <li class="active"><a data-toggle="tab" href="#home">Description</a></li>
			  <li><a data-toggle="tab" href="#menu1">Reviews</a></li>
			</ul>

			<div class="container tab-color">
			<div class="tab-content">
			  <div id="home" class="tab-pane fade in active topmarg">
				<div class="row">
				  <div class="col-md-3 tar">Subject:</div>
				  <div class="col-md-8">{{bookinfo.subject}}</div>
				</div>
				<div class="row">
				  <div class="col-md-3 tar">Format Available:</div>
				  <div class="col-md-8">{{bookinfo.format}}</div>
				</div>
				<div class="row">
				  <div class="col-md-3 tar">Year of Publication:</div>
				  <div class="col-md-8">{{bookinfo.year}}</div>
				</div>
				<div class="row">
				  <div class="col-md-3 tar">Published by:</div>
				  <div class="col-md-8">{{bookinfo.publisher}}</div>
				</div>
				<div class="row">
				  <div class="col-md-3 tar">ISBN:</div>
				  <div class="col-md-8">{{bookinfo.isbn10}}</div>
				</div>
				<div class="row topmarg">
					<div class="col-md-3 tar">About this book:</div>
				</div>
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-10 description bb">"<strong>{{bookinfo.title}}</strong> lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</div>
					
				</div>
				<div class="row bb">
					<div class="col-md-5 tar">{{bookinfo.stock}} left in stock.</div>
					<div class="col-md-3 tac">Price: ${{bookinfo.price}}0</div>
					<div class="col-md-4">
						<button type="button" id="checkout" class="btn glyphicon glyphicon-shopping-cart aria-label="Left Align"" data-toggle="modal" data-target="#orderModal"> ORDER NOW           
          				</button>
					</div>
				</div>

			  </div>
			  <div id="menu1" class="tab-pane fade">
			  	
			  	<div class="row topmarg">
			  		<div class="col-md-1"></div>
				  	<div class="col-md-9"><h5>This book has a total of <strong>{{fbnum}}</strong> feedback(s) with average rating <strong>{{fbscore}}/10.</strong></h5></div>
				</div>
				<form role="form" action="" method="post">
				    {% csrf_token %}
				   
				    <input id="id_book" min="10" max="10" name="id_book" type="hidden" value="{{bookinfo.isbn10}}"readonly>	
				    <div class= "row">
				    	<div class="col-md-1">
				    	</div>
					    <div class="col-md-4">
							<table>
						    {{ display.form.as_table }}
							</table>
						</div>
						<div class="col-md-6">
					    	<button id="topn" type="submit" class="btn btn-default">Get Top-N Useful Feedbacks</button>
						</div>
					</div>
					</form>

				<div class="scroll-review">
				  	{% for entry, fb in feedback %}
				  		<div class="row topmarg">
				  			<div class="col-md-1"></div>
					  		<div class="col-md-3 score">Score: {{fb.score}} / 10</div>
				  			
						</div>
						<div class="row">
							<div class="col-md-1"></div>
					  		<div class="col-md-10 reviewer"><em>Reviewed by - {{fb.login_id}}</em></div>
				  			
						</div>
						<div class="row">
							<div class="col-md-1"></div>
					  		<div class="col-md-9 opinion">{{fb.opinion}}</div>
				  			
						</div>
						<div class="row">
							<div class="col-md-1"></div>
					  		<div class="col-md-9 reviewer opinion">Average Usefulness Rating: <strong>{{entry}}/2</strong></div>
				  			
						</div>
						<div class="row">
							<div class="col-md-1"></div>
					  		<div class="col-md-9 reviewer opinion">Is this review helpful? <a href="javascript:void(0)" class="announce" data-id="{{bookinfo.isbn10}}/*{{bookinfo.title}}/*{{fb.login_id}}" data-target="#usefulnessModal">Help to rate this feedback!</a></div>
				  			
						</div>
						
				    {%endfor%}


					
					
				</div>
			  </div>
			</div>
			</div>

		</div>
    </div>
  </div>
  <!-- Modal -->
	<div id="orderModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">

	    <!-- Modal content-->
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal">&times;</button>
	        <h4 class="modal-title">Ordering <strong>{{bookinfo.title}}</strong></h4>
	        <h5>Please check the following and indicate the number of copies you would like to order. </h5>
	      </div>
	      <div class="modal-body">
	      	<div class="well">
	      	<div>Book: {{bookinfo.title}}</div>
	      	<div>Written By: {{bookinfo.authors}}</div>
	        <div>Currently in stock: {{bookinfo.stock}}</div>
	        <div>Price: ${{bookinfo.price}}0</div>
	        	<label>Order Quantity: </label>
	        		<input type="number" name="quantity" id="quantity" class="tar num" value="1" min="1" max="{{bookinfo.stock}}"/>

	    </div>
	      </div>
	      <div class="modal-footer">
	        <div class="form-group">
	          <button class="btn btn-primary pull-right" ng-click="order({{bookinfo.isbn10}})">CONFIRM ORDER</button>
	        </div>
	      </div>
	    </div>

	  </div>
	</div>



	
  {% include 'javascripts.html' %}
  <script>
  		console.log("in book_info.html")
  		/*console.log(($("#usefulnessModal").data('bs.modal') || {isShown: false}).isShown)
  		console.log(($("#feedbackModal").data('bs.modal') || {isShown: false}).isShown)
  		console.log(($("#orderModal").data('bs.modal') || {isShown: false}).isShown)*/
		$(document).ready(function(){
			$(".announce").click(function(){
				var text = $(this).data('id')
				var book = text.split("/*")
				$("#id_ISBN10").val(book[0]);
				$("#id_title").val(book[1]);
				$("#id_rating_on").val(book[2]);

				$("#usefulnessModal").modal('show');
			});
		});

	</script>
</body>
</html>

thinkster-django-angular-boilerplate/templates/book_update_form.html
<!DOCTYPE html>

<html ng-app="thinkster">
<head>
  <title>thinkster-django-angular-boilerplate</title>

  <base href="/" />

  {% include 'stylesheets.html' %}
</head>

<body >
  {% include 'navbar.html' %}
  <div class="container">
  	<h4>{{msg}}</h4>
  		<div class="well">
    	<div class="margauto">
    		<h1>Edit Book Stock</h1>
  <form action="" method="post" >{% csrf_token %}
	<table class="etable">
    {{ form.as_table }}
	</table>
	<div class="row smallmarg">
				<div class="col-md-9">
				</div>
				<div class="col-md-3">
					<button id="up" class="btn">Update</button>
				</div>
			</div>
</form>
	
</div>
    	</div>
  {% include 'javascripts.html' %}
</body>
</html>

thinkster-django-angular-boilerplate/templates/confirmation.html
<!DOCTYPE html>

<html ng-app="thinkster">
<head>
  <title>thinkster-django-angular-boilerplate</title>

  <base href="/" />

  {% include 'stylesheets.html' %}
</head>

<body>
  {% include 'navbar.html' %}
  <div class="container">
  	<div class="well">
	  <h4>Your Order Has Been Confirmed!</h4>
	  <h4>Here are some books recommended for you!</4>
	  <h5>Others who bought this also bought...</h5>
	  
	  {% for book in recommended %}
	  <a href="/book/{{book.isbn10}}"> <img src="static/images/{{book.image}}" class="smallpic"> </a>
	  {% endfor %}
	</div>
  </div>
  {% include 'javascripts.html' %}
</body>
</html>

thinkster-django-angular-boilerplate/templates/user_info.html
<!DOCTYPE html>

<html ng-app="thinkster">
<head>
  <title>thinkster-django-angular-boilerplate</title>

  <base href="/" />

  {% include 'stylesheets.html' %}
</head>

<body>
  {% include 'navbar.html' %}
  	  <!-- Modal -->
	<div id="feedbackModal" class="modal fade" role="dialog">
	  <div class="modal-dialog">

	    <!-- Modal content-->
	    <div class="modal-content">
	    	<form role="form" action="" method="post">
	      <div class="modal-header">
	        	<button type="button" class="close" data-dismiss="modal">&times;</button>
	        	<h4 class="modal-title"> <strong>Feedback</strong></h4>
	        	<h5>Please enter your feedback for <span id="BookId"></span><span id="Title"></span> here. Give it a score from 0 (terrible) to 10 (wonderful).</h5>
	      </div>
	      <div class="modal-body">
		      	<div class="well">
		      	
				
				
				    {% csrf_token %}	
					<table class="addtable">
				    {{ form.as_table }}
					</table>
					

	   			 </div>

	  </div>
	  <div class="modal-footer">
        <div class="form-group">
          <button class="btn btn-primary pull-right"  type="submit">FEEDBACK</button>
        </div>
	  </div>
	  </form>
	      		
	</div>
</div>
</div>
  	<div class="container">
		<div class="well">
			<div class="acc">
			<ul class="nav nav-tabs">
			  <li class="active"><a data-toggle="tab" href="#acc">Account Information</a></li>
			  <li><a data-toggle="tab" href="#oh">Order History</a></li>
			  <li><a data-toggle="tab" href="#fh">Feedback History</a></li>
			  <li><a data-toggle="tab" href="#uh">Usefulness Rating History</a></li>

			</ul>
			<h4>{{msg}}</h4>
			<div class="container">
			<div class="tab-content">
			  <div id="acc" class="tab-pane fade in active topmarg">
			  	<div class="leftmarg">
			  		<h1>Account Page</h1>
			 	 </div>
			  	<div class="row smallmarg">
			  		<div class="col-md-1">
			  		</div>
			  		<div class="col-md-2">
			  			<div>Full Name:</div>
			  		</div>
			  		<div class="col-md-3">
			  			<div>{{ account_info.full_name }}</div>
			  		</div>
			  	</div>
			  	<div class="row smallmarg">			  		
			  		<div class="col-md-1">
			  		</div>
			  		<div class="col-md-2">
			  			<div>Username:</div>
			  		</div>
			  		<div class="col-md-3">
			  			<div>{{ account_info.username }}</div>
			  		</div>
			  	</div>
			  	<div class="row smallmarg">
			  		<div class="col-md-1">
			  		</div>
			  		<div class="col-md-2">
			  			<div>Credit Card Number:</div>
			  		</div>
			  		<div class="col-md-3">
			  			<div>{{ account_info.credit_card }}</div>
			  		</div>
			  	</div>
			  	<div class="row smallmarg">
			  		<div class="col-md-1">
			  		</div>
			  		<div class="col-md-2">
			  			<div>Address:</div>
			  		</div>
			  		<div class="col-md-3">
			  			<div>{{ account_info.address }}</div>
			  		</div>
			  	</div>
			  	<div class="row smallmarg">
			  		<div class="col-md-1">
			  		</div>
			  		<div class="col-md-2">
			  			<div>Phone Number:</div>
			  		</div>
			  		<div class="col-md-3">
			  			<div>{{ account_info.phone }}</div>
			  		</div>
			  	</div>
			  	<div class="row smallmarg">
			  		<div class="col-md-4">
			  		</div>
			  		<div class="col-md-2">
			  			<button id="editbtn" type="button" class="btn btn-default" onclick = "location.href='/edit/'">Edit</button>	
			  		</div>
			  		
			  	</div>
			  				
			  </div>



			  <div id="oh" class="tab-pane fade">
			  	<div class="leftmarg topmarg">
			  		<h1>Order History</h1>
			  	</div>
			  	<div class="atable smallmarg utable">
				  	<table class="ftable">
				  		<tr>
				  			<th>S/N.</th>
				  			<th>Date of Order</th>
				  			<th>Book Title</th>
				  			<th>Price ($)</th>
				  			<th>Quantity Ordered</th>
				  			<th>Feedback Done?</th>
				  		</tr>

				  		{% if orders %}
							{% for orderhistory, book, book_ordered, isFB in orders reversed %}
							<tr>
								<td> </td>
								<td>{{ orderhistory.order_date }}</td>
								<td><a href="/book/{{book.isbn10}}">{{ book.title }}</a></td>
								<td>{{ book.price }}</td>
								<td>{{ book_ordered.0.quantity }}</td>
								{% if isFB %}
									<td><a href="javascript:void(0)" class="feed"  data-target="#feedbackModal" data-id="{{book.isbn10}}/*{{book.title}}">Feedback Here!</a></td>
								{% else %}
									<td> Done Feedback </td>
								{% endif %}
								
							</tr>
							{% endfor %}
						{% else %}
							<div>You have not ordered anything!</div>
						{% endif %}
					</table>
				</div>
			  	
			  </div>

			  <div id="fh" class="tab-pane fade">
			  	<div class="leftmarg topmarg"><h1>Feedback</h1></div>
			  	<div class="atable smallmarg utable">
				  	<table class="ftable">
				  		<tr>
				  			<th>S/N.</th>
				  			<th>Date of Feedback</th>
				  			<th>Book Title</th>
				  			<th>Score Given</th>
				  			<th>Your Feedback</th>
				  		</tr>
				  		{% if feedbacks %}
							{% for feedback, book in feedbacks %}
					  		<tr>
								<td> </td>
								<td>{{ feedback.entry_date }}</td>
								<td><a href="/book/{{book.isbn10}}">{{ book.title }}</a></td>
								<td>{{ feedback.score }}</td>
								<td>{{ feedback.opinion }}</td>
							</tr>
							{% endfor %}
					</table>

						
						{% else %}
						<div>You have no feedback!</div>
						{% endif %}
				  	
				  </div>
				</div>


			   <div id="uh" class="tab-pane fade">
					<div class="leftmarg topmarg"><h1>Ratings</h1></div>
					<div class="atable smallmarg utable">
					  	<table class="ftable">
					  		<tr>
					  			<th>S/N.</th>
					  			<th>You Rated a Feedback On Book Titled</th>
					  			<th>Feedback From</th>
					  			<th>Feedback</th>
					  			<th>Usefulness Rating Given</th>
					  			<th>Your Rating On This</th>
					  		</tr>
					  		{% if ratings %}
								{% for rating, customer_ratee, book, feedback in ratings %}
						  		<tr>
									<td> </td>
									<td><a href="/book/{{book.isbn10}}">{{ book.title }}</a></td>
									<td>{{ customer_ratee.username }}</td>
									<td>{{ feedback.opinion }}</td>
									<td>{{ rating.usefulness }}</td>
									{% if rating.usefulness == 0 %}
										<td>You thought this feedback was useless...</td>
									{% elif rating.usefulness == 1 %}
										<td>You thought this feedback was average.</td>
									{% else %}
										<td>You thought this feedback was good!</td>
									{% endif %}
								</tr>
								{% endfor %}
						</table>

							
							{% else %}
							<div>You have no rated feedback!</div>
							{% endif %}
					  	
					  </div>
					
								  	
			  	
			  </div>
			</div>
			</div>

			</div>
			
			

			

		</div>
	</div>


  {% include 'javascripts.html' %}
  	<script>
		$(document).ready(function(){
			$(".feed").click(function(){
				console.log("I AM TESTING FEEDBACK MODAL")
				var text = $(this).data('id')
				var book = text.split("/*")
				$("#id_ISBN10").val(book[0]);
				$("#id_title").val(book[1]);

				document.getElementById("BookId").innerHTML = "("+book[0]+") ";
				document.getElementById("Title").innerHTML = book[1];
				$("#feedbackModal").modal('show');
			});
		});
	</script>
</body>
</html>